stages:
  run_model:
    cmd: python scripts/run_model_pipe_A.py
    deps:
    - ../../src/
    - /home/tim/Workspaces/proteolizard-algorithm/python/
    - /home/tim/Workspaces/proteolizard-data/python/
    - scripts/run_model_pipe_A.py
    params:
    - run_model.data_path
    - run_model.feature_ids
    - run_model.model_name
    - run_model.save_traces
    plots:
    - output_data/plot_metrics/metrics_plot_dict.json:
        template: plot_templates/histogram_template.json
        title: Histogram of NUTS Step Size
        x: step_size
        x_label: NUTS Step Size
        
    - output_data/plots
    metrics:
    - output_data/metrics/metrics.json
    outs:
    - output_data/inference_data
plots:
  acceptance_rate_density:
    title: Density Estimation of Acceptance Rate
    x: 
      output_data/plot_metrics/metrics_plot_dict.json: acceptance_rate,
    template: plot_templates/density_template.json,
    x_label: Acceptance Rate