stages:
  run_model:
    cmd: python scripts/run_model_pipe_A.py
    deps:
    - ../../src/
    - /home/tim/Workspaces/proteolizard-algorithm/python/
    - /home/tim/Workspaces/proteolizard-data/python/
    - scripts/run_model_pipe_A.py
    params:
    - run_model.data_path
    - run_model.feature_ids
    - run_model.model_name
    - run_model.save_traces
    plots:
    - output_data/plots
    - output_data/plot_metrics/metrics_plot_dict.json:
        y: acceptance_rate
        template: pipelines/pipe_A/plot_templates/histogram_template.json
    - output_data/plot_metrics/test.json:
        x: x
        y: y
        # template path relative to .dvc folder!
        template: pipelines/pipe_A/plot_templates/bar_template.json
    metrics:
    - output_data/metrics/metrics.json
    outs:
    - output_data/inference_data    
    - output_data/plotly